export const ADD_POST_ERROR = 'ADD_POST_ERROR';
export const ADD_POST_LOADING = 'ADD_POST_LOADING';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';
export const EDIT_POST_LOADING = 'EDIT_POST_LOADING';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';

export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_LOADING = 'FETCH_POST_LOADING';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';